### ISSUE TITLE
The important gauges are zero.

### ISSUE THREAD

**Issue by hfuhuang** [AndreyVMarkelov/prom-confluence-exporter#14]
In my test environment, I got zero gauges, even there are pages and blog and login users:

\# HELP confluence_current_contents_gauge Current Contents Gauge
\# TYPE confluence_current_contents_gauge gauge
confluence_current_contents_gauge 0.0
\# HELP confluence_global_spaces_gauge Global Spaces Gauge
\# TYPE confluence_global_spaces_gauge gauge
confluence_global_spaces_gauge 0.0
\# HELP confluence_personal_spaces_gauge Personal Spaces Gauge
\# TYPE confluence_personal_spaces_gauge gauge
confluence_personal_spaces_gauge 0.0
\# HELP confluence_one_hour_active_users_gauge Users Login One Hour Ago Gauge
\# TYPE confluence_one_hour_active_users_gauge gauge
confluence_one_hour_active_users_gauge 0.0
\# HELP confluence_today_active_users_gauge Users Login Today Gauge
\# TYPE confluence_today_active_users_gauge gauge
confluence_today_active_users_gauge 0.0
\# HELP confluence_total_attachment_size_gauge Total Attachments Size Gauge
\# TYPE confluence_total_attachment_size_gauge gauge
confluence_total_attachment_size_gauge 0.0
\# HELP confluence_pages_gauge Total Pages Gauge
\# TYPE confluence_pages_gauge gauge
confluence_pages_gauge 0.0
\# HELP confluence_blogposts_gauge Total BlogPosts Gauge
\# TYPE confluence_blogposts_gauge gauge
confluence_blogposts_gauge 0.0

On the configuration page, it said:
Last execution: not yet executed

**Comment by hfuhuang** [comment]
The error in log file showed:
 -- url: /confluence/rest/plugins/1.0/ | referer: https://adnconflu-int-001.zh.adnovum.ch:8444/confluence/plugins/servlet/upm | traceId: 7d51b46505738e08 | userName: admin
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'confluence.contentproperties' doesn't exist
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:411)
	at com.mysql.jdbc.Util.getInstance(Util.java:386)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1054)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4190)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:4122)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2570)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2731)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2812)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2761)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1612)
	at com.mchange.v2.c3p0.impl.NewProxyStatement.executeQuery(NewProxyStatement.java:327)
	at ru.andreymarkelov.atlas.plugins.promconfluenceexporter.manager.ScheduledMetricEvaluatorImpl.calculateTotalAttachmentSize(ScheduledMetricEvaluatorImpl.java:281)
	at ru.andreymarkelov.atlas.plugins.promconfluenceexporter.manager.ScheduledMetricEvaluatorImpl.access$100(ScheduledMetricEvaluatorImpl.java:39)
	at ru.andreymarkelov.atlas.plugins.promconfluenceexporter.manager.ScheduledMetricEvaluatorImpl$2.run(ScheduledMetricEvaluatorImpl.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-04-30 11:53:29,186 WARN [http-bio-8443-exec-13] [common.security.jersey.XsrfResou

See also:
https://confluence.atlassian.com/confkb/confluence-throws-table-table-name-doesn-t-exist-error-after-syncing-with-external-directory-829918934.html

**Comment by hfuhuang** [comment]
@AndreyVMarkelov : I found the problem. In our installation the table names are CONTENTPROPERTIES and CONTENT, but the plugin hard-codes them in low case:

> 
private static final String ATTACHMENT_SQL = "SELECT sum(LONGVAL) FROM contentproperties cp JOIN content c ON cp.contentid = c.contentid WHERE c.contenttype = 'ATTACHMENT' AND cp.propertyname = 'FILESIZE'";
    private static final String PAGE_SQL = "SELECT count(CONTENTID) FROM content WHERE contenttype = 'PAGE' AND prevver IS NULL AND content_status = 'current'";
    private static final String BLOGPOST_SQL = "SELECT count(CONTENTID) FROM content WHERE contenttype = 'BLOGPOST' AND prevver IS NULL AND content_status = 'current'";
>

**Comment by AndreyVMarkelov** [comment]
Hi. Good catch. MySql? I will try locally to do conpatible for all

ср, 2 Май 2018 г., 13:24 hfuhuang <notifications@github.com>:
